name: libraries

networks:
  creadf:
    external: true

services:
  library:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: safethrow
    volumes:
      - ../:/var/www/html
    networks:
      - creadf
    env_file:
      - docker.env